### ISSUE TITLE
session1: section 4.1 - redraft joins section

### ISSUE THREAD

**Issue by jayware9** [DataScienceScotland/intro_to_r#52]
could make some of the merge/join commands incomplete to increase interaction with attendees rather than just running through them all 

https://github.com/DataScienceScotland/intro_to_r/blob/17b78f13c38c16da9f22902a802a29f426d58f68/session1/intro_to_r_training_incomplete.Rmd#L909

**Comment by jrobertson-sg** [comment]
Sorry for the delay folks. The new sections look like good class discussion or self-completion prompts - nice work
