### ISSUE TITLE
session 3: slide/image to explain project

### ISSUE THREAD

**Issue by jayware9** [DataScienceScotland/intro_to_r#64]
develop a document in Powerpoint or equivalent that can be added to the materials for the presenters to use.

The problem as it stands is quite complex with the applications, reviews and lagged reviews/appeals all in one go. A couple of suggestions were made to reduce complexity and possible barrier to understanding for course attendees: 

* One suggestion was to reduce the number of components of the problem by removing the appeals component, which is solved via the same approach as the review component  
* An alternative suggestion was to break the problem in two parts, first by introducing the basic application process, loading the data for that and calculating FTE. Then, after this has been completed, a second part to the problem is introduced where the ideas of appeals and reviews are added and FTE requirements have to be recalculated on the basis of this

**Comment by Talexis77** [comment]
I think the FTE calculation on the diagram needs amending. The code shows this as:
 fte = (total_review_processing_time + app_processing_time)/(days * 444 * .75))

However the diagram in the housekeeping folder shows this as  fte_i = total_processing_time*days * work minutes per day* productivity))
