### ISSUE TITLE
session 3: amend code to reflect any changes/simplifications we make to the session 3 project 

### ISSUE THREAD

**Issue by jayware9** [DataScienceScotland/intro_to_r#65]
The problem as it stands is quite complex with the applications, reviews and lagged reviews/appeals all in one go. A couple of suggestions were made to reduce complexity and possible barrier to understanding for course attendees: 

* One suggestion was to reduce the number of components of the problem by removing the appeals component, which is solved via the same approach as the review component  
* An alternative suggestion was to break the problem in two parts, first by introducing the basic application process, loading the data for that and calculating FTE. Then, after this has been completed, a second part to the problem is introduced where the ideas of appeals and reviews are added and FTE requirements have to be recalculated on the basis of this

**Comment by Talexis77** [comment]
Tom to update Analysis script and worked solution file following discussion with Iris
Iris to update the create data script which generates the benefits csv files and flow chart (problem structure) diagram and add it to rmd (intro_to_R_session3 file)

**Comment by irisoren-sg** [comment]
@Talexis77 I have pushed the new script and benefit csvs to the branch rework_session_3

**Comment by irisoren-sg** [comment]
@talexis77 We now need to add assumptions around the processing times for initial nc and coc. I will add this to the Rmd later and push

**Comment by irisoren-sg** [comment]
@Talexis77 updated Rmd pushed

**Comment by Talexis77** [comment]
In the intro_to_R_session3.Rmd, review_time is now defined twice and has different values. I think we need to change the name of one of these objects, because we have one stage where the applications first come in (initial_review_time?), a proportion of them then need reviewed so we then need review_time. That was my understanding anyway!

**Comment by irisoren-sg** [comment]
Thanks @Talexis77 .  I have changed it to app_processing_time and review_processing_time
