### ISSUE TITLE
add blurb for course

### ISSUE THREAD

**Issue by jayware9** [DataScienceScotland/intro_to_r#76]

**Comment by jrobertson-sg** [comment]
How does this sound Jaye?

> The Scottish Government Introduction to R course will help you get started using R for data manipulation and analysis. 
> The training will take place over Teams. Over three half-day sessions you will work with experienced R-user colleagues to learn the simple but powerful "tidyverse" suite in RStudio. 
> This short course also includes introductory material on the use of "ggplot" to produce charts, and RMarkdown - a widely-used system for creating typeset documents with embedded data analysis. 
> Before the classroom sessions there will be a start-up session where you can get help setting up the R software needed for the course.
> This course has been designed by and for Scottish Government analysts. It will provide a foundation for future applications of the R language in statistical modelling, RShiny apps and Reproducible Analytical Pipelines.
> [_Optional_: We are also trialling a self-study option for this course and volunteers are being sought to review the material outside of a classroom setting.]

**Comment by jayware9** [comment]
@jrobertson-sg thanks Jamie, this looks great. I've added the blurb to an MD file in the housekeeping folder so we have it for future.

**Comment by jrobertson-sg** [comment]
Cheers @jayware9 , I've sent this on to Ilze now
