### ISSUE TITLE
Amend introduction to pipes

### ISSUE THREAD

**Issue by jayware9** [DataScienceScotland/intro_to_r#86]
Use a simpler example such as filter to introduce pipes, as group_by is maybe a bit too complicated to tack on to that

**Comment by Talexis77** [comment]
Apologies I accidentally committed directly to main when I made amendments for this. I don't think anything I've done will be too controversial though, so maybe someone could just review the changes I made if you look at the latest commit on main?

**Comment by jayware9** [comment]
Thanks @Talexis77, I'll take a look
